### ISSUE TITLE
Consensus building for 1D

### ISSUE THREAD

**Issue by kylacochrane** [CSB5/INC-Seq#10]
Is it possible to use INC-seq with the NanoPore 1D kits? I used the 1D 16S PCR barcoding kit to generate full length 16S reads. 

I run this code (with my demultiplexed fasta file);

$ ./inc-seq.py -i ~/$.fasta -m 1000 -o consensus.fa 

And this is the output:
---------- Processing read 1 ----------
Max number of segments found: 0 
Consensus construction failed!
---------- Processing read 2 ----------
Max number of segments found: 0 
Consensus construction failed!
...etc 

Any help would be greatly appreciated.
Thanks so much!

**Comment by lch14forever** [comment]
Hi, 

I am afraid that standard 16S full length library will not work. INC-Seq needs tandem repeats in the reads generated using Rolling Circle Amplification.

Regards,
Chenhao
