### ISSUE TITLE
Error with pbdagcon

### ISSUE THREAD

**Issue by yangao07** [CSB5/INC-Seq#7]
Hi, 
I just got this error when running INC-seq.py with following parameters:
`python ~/software/INC-Seq/inc-seq.py   --copy_num_thre 2 -m 100 --anchor_cov 0.7 --length_difference 0.1 --seg_cov 0.7 -i read.fa -o cons.fa`

> ---------- Processing read 437 ----------
> Max number of segments found: 6 
> Number of segments of the candidate strech: 5
> Candidate read found!
> Warning: PBDAGCON timeout! Trimming 988 base(s).
> Traceback (most recent call last):
>   File "/u/home/y/yangao/software/INC-Seq/inc-seq.py", line 160, in <module>
>     sys.exit(main(sys.argv[1:]))
>   File "/u/home/y/yangao/software/INC-Seq/inc-seq.py", line 147, in main
>     args.seg_cov, args.iterative)
>   File "/u/home/y/yangao/software/INC-Seq/inc-seq.py", line 24, in callBuildConsensus
>     seg_cov, iterative)
>   File "/u/home/y/yangao/software/INC-Seq/utils/buildConsensus.py", line 289, in consensus_blastn
>     consensus = pbdagcon(tmpname+'.m5', 0)
>   File "/u/home/y/yangao/software/INC-Seq/utils/buildConsensus.py", line 220, in pbdagcon
>     stdout = pbdagcon(m5, t+1)
>   File "/u/home/y/yangao/software/INC-Seq/utils/buildConsensus.py", line 220, in pbdagcon
>     stdout = pbdagcon(m5, t+1)
>  ... ...
> File "/u/home/y/yangao/software/INC-Seq/utils/buildConsensus.py", line 220, in pbdagcon
>     stdout = pbdagcon(m5, t+1)
>   File "/u/home/y/yangao/software/INC-Seq/utils/buildConsensus.py", line 207, in pbdagcon
>     proc = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
>   File "/u/home/y/yangao/.local/lib/python2.7/subprocess.py", line 390, in __init__
>     errread, errwrite)
>   File "/u/home/y/yangao/.local/lib/python2.7/subprocess.py", line 888, in _execute_child
>     if isinstance(args, types.StringTypes):
> RuntimeError: maximum recursion depth exceeded while calling a Python object
> 

Could you help me with that?
Thanks!

Yan

**Comment by lch14forever** [comment]
Hi,

Which PBDAGCON version are you using? Will upgrade to the latest version help?

How long is your template? I can see that trimming 988 bases is for sure not a good idea. Maybe I can terminate the recursion earlier and skip the read.

Chenhao

**Comment by lch14forever** [comment]
I have pushed a quick fix. You might want to try it out.

**Comment by yangao07** [comment]
Hi,

It is wired that I could get consensus result when running it on my laptop, but nothing on the server.
Here is one read:
[test.fa.gz](https://github.com/CSB5/INC-Seq/files/1565264/test.fa.gz)

I run  INC-seq.py with following parameters:
`python ~/software/INC-Seq/inc-seq.py --copy_num_thre 2 -m 100 --anchor_cov 0.7 --length_difference 0.1 --seg_cov 0.7 -i read.fa -o cons.fa `

Thanks!

**Comment by lch14forever** [comment]
I tested your example and did not get the consensus either. I did notice PBDAGCON had inconsistent behavior across different platforms. I have no ideas why. If it generates more consensus on your laptop, I would suggest just run it there.

Chenhao.
