### ISSUE TITLE
PBDAGCON failed (trimmed more than 100 bases)

### ISSUE THREAD

**Issue by s-j-mc** [CSB5/INC-Seq#8]
Hi,
I have just tried running the basic usage example: 

python inc-seq.py -i data/inc_seq_test_read.fa -o consensus.fa

I get the following error message:

---------- Processing read 1 ----------
Max number of segments found: 20
Number of segments of the candidate strech: 20
Candidate read found!
PBDAGCON failed (trimmed more than 100 bases)!
Consensus construction failed!

This is the same error message I receive when running my own samples through this pipeline. Have you got any idea what might be causing this?

Thanks,
Sam

**Comment by lch14forever** [comment]
It is a problem with PBDAGCON. Please try to compile it  (https://github.com/PacificBiosciences/pbdagcon) and replace the version in utils/ with the binary. It seems to me that PBDAGCON is broken and I will see if there is a way to fix this.

====
update: I think one solution I can find is to install PBDAGCON with apt-get (This limits it utility to ubuntu or debian linux machine).

```sh
sudo apt install pbdagcon
ln -s `which pbdagcon` /PATH/TO/INC-Seq/REPO/utils/
```

I have added my version compiled on Ubuntu 16.04 to the latest commit.

**Comment by s-j-mc** [comment]
Thanks, I'm currently running my data with `--aligner poa`, which seems to be working well for now. I will attempt what you said and see if anything changes.

**Comment by lch14forever** [comment]
POA will build the consensus without running PBDAGCON. However, what I found was it had lower consensus accuracy somehow.

**Comment by lch14forever** [comment]
I have implemented a [minimap2+racon framework](https://github.com/CSB5/INC-Seq/tree/py3). You can give it a try if you wish.

**Comment by s-j-mc** [comment]
Thanks a lot for the help. I did intend to look into minimap2 + racon, so the implementation you have included is very welcome! I am currently running my data through the minimap2 + racon framework as we speak.
